name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mv clients/rust/* .
      - run: rm -rf clients config
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
